<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29001" started-at="2016-10-09T19:20:32Z" finished-at="2016-10-09T19:21:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29001" started-at="2016-10-09T19:20:32Z" finished-at="2016-10-09T19:21:01Z">
      <class name="TestSuite1.TC0001">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestSuite1.TC0001@725bef66]" name="setUp" is-config="true" duration-ms="6915" started-at="2016-10-09T15:20:32Z" finished-at="2016-10-09T15:20:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="tc0001()[pri:0, instance:TestSuite1.TC0001@725bef66]" name="tc0001" duration-ms="15705" started-at="2016-10-09T15:20:39Z" finished-at="2016-10-09T15:20:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed check for country list being sorted in  BaseClass.VerifyCountryListSorted.: Lists differ at element [1]: Australia != Brazil expected [Australia] but found [Brazil]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed check for country list being sorted in  BaseClass.VerifyCountryListSorted.: Lists differ at element [1]: Australia != Brazil expected [Australia] but found [Brazil]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at Dash.BaseClass.VerifyCountryAndVendorListSorted(BaseClass.java:222)
	at TestSuite1.TC0001.tc0001(TC0001.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc0001 -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:TestSuite1.TC0001@725bef66]" name="closeDriver" is-config="true" duration-ms="6364" started-at="2016-10-09T15:20:55Z" finished-at="2016-10-09T15:21:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- TestSuite1.TC0001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
